DROP TABLE IF EXISTS ratings CASCADE;
--  CREATE RATINGS --
CREATE TABLE ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  movie_api_id INTEGER,
  rating INTEGER NOT NULL
);
